### ISSUE TITLE
Icons missing in PDF format

### ISSUE THREAD

**Issue by bpesquet** [aruberto/fresh-theme-bootstrap#4]
Hi,

I'm using this theme for my HMR-powered resume, and it's great. Thanks for your work.

I have one little issue : when generating output in PDF format with wkhtmltopdf, the Font Awesome icons don't show up (see screencap below). They work fine in HTML format.

![capture d ecran 2016-04-11 a 18 26 39](https://cloud.githubusercontent.com/assets/1837749/14434445/10d5d526-0013-11e6-8015-489b8b446567.png)

**Comment by aruberto** [comment]
Icons show correctly for me when I generate PDF:

![image](https://cloud.githubusercontent.com/assets/9933826/15271499/653c2a44-1a1b-11e6-8369-828cf595c95e.png)

Were you connected to internet when generating PDF? The icons are Font Awesome icons I'm including in HTML via cdn:

```
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"></link>
```

Perhaps issue is environmental? I am generating on Windows 10 with node 5.10.1. How are you running PDF generation?

**Comment by bpesquet** [comment]
Thanks for your answer and sorry for the lack of details in the issue.

The problem was most certainly environmental. I was generating on OS X Mavericks with wkhtmltopdf 0.12.3 and an active internet connection. I updated to El Capitan recently and just ran a test : it works fine now.
