### ISSUE TITLE
Unable to build: Error: TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by leinss** [aruberto/fresh-theme-bootstrap#7]
Hi, 

trying to build resumes with fresh-theme-bootstrap results on my ubuntu machine in a Type-Error.
Please see the log, other hackmyresume builds work.

Any suggestions?

```
*** HackMyResume v1.9.0-beta ***
Reading FRESH resume: resume.json
Applying FRESH-THEME-BOOTSTRAP theme (5 formats)
Generating HTML resume: out/bootstrap/superhero/resume.html
An error occurred during template invocation.
   TypeError: Cannot read property 'operator' of undefined
Generating PDF  resume: out/bootstrap/superhero/resume.pdf
An error occurred during template invocation.
   TypeError: Cannot read property 'operator' of undefined
Generating JSON resume: out/bootstrap/superhero/resume.json
Generating YML  resume: out/bootstrap/superhero/resume.yml
Generating PNG  resume: out/bootstrap/superhero/resume.png
Error: TypeError: Cannot read property 'filter' of undefined
```

**Comment by aruberto** [comment]
@Caruso33 Does error occur when using HackMyResume v1.8.0 ?

Only place 'operator' attribute is used is in HackMyResume compare function

https://github.com/hacksalot/HackMyResume/blob/ab6e7ee1a0f55608b531f4e644c298426291bb17/src/helpers/generic-helpers.js#L535-L555

Perhaps that handlebars helper is not working correctly in newer version.

**Comment by leinss** [comment]
Perfect, yes that seems to break it.
On 1.8.0 the build works fine.

Thanks for your reply.
